[package]

name = "piston_research"
version = "0.1.0"


[[bin]]
name = "piston_research"

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.42.0"
pistoncore-glutin_window = "0.69.0"
piston2d-opengl_graphics = "0.81.0"
piston_window = "*"